### ISSUE TITLE
Preferences Dialog: Warn user if they are about to discard changes

### ISSUE THREAD

**Issue by nshcat** [glscopeclient/scopehal-apps#269]
Currently, when the user clicks on "Cancel", the dialog will not warn them about any changes that would be lost.

The message box could also list the settings that have been changed, since we have that information.

Maybe something like this:

"The following changes are about to be discarded, are you sure?
   Appearance > Waveforms > Color Cursor 1
   Appearance > Waveforms > Color Cursor 2

yes/no"

**Comment by azonenberg** [comment]
Closing because ngscopeclient now applies preference changes modelessly, so there's no concept of cancel/apply anymore.
