### ISSUE TITLE
[Windows] Going into fullscreen mode and out again causes the window title bar to permanently disappear

### ISSUE THREAD

**Issue by nshcat** [glscopeclient/scopehal-apps#273]
Only reproducible on Windows for me so far.

**Comment by azonenberg** [comment]
Meanwhile for me on my WaveRunner, fullscreen mode makes the GUI stop updating *and* doesn't truly fullscreen. Sounds like it's bugged all around, possibly >1 issue.

**Comment by azonenberg** [comment]
Wontfix on glscopeclient, works fine in ngscopeclient now.
