### ISSUE TITLE
Marker issue

### ISSUE THREAD

**Issue by bvernoux** [glscopeclient/scopehal-apps#435]
When using Marker all work fine visually but when saving/restoring a *.scopesession the markers are broken with invalid values(negatives) and when the scopesession is loaded nothing is displayed (even the waveform).
Issue reproduced with latest version of glscopeclient https://github.com/glscopeclient/scopehal-apps/commit/af2c022e85fbb9905960ebc272c86d3319ccc196 on windows 10 (using https://github.com/glscopeclient/scopehal-apps/suites/6973742607/artifacts/272626580)
File used are based on Rigol MSO5K import (with 2 chan) I can provide them if required

**Comment by azonenberg** [comment]
Please attach test files and screenshots.

**Comment by azonenberg** [comment]
Also, please check if the "nothing displayed on waveform" issue is related to https://github.com/glscopeclient/scopehal-apps/commit/524c645edb20eccabaa7e463b915af3647d72aea.

Does reverting to prior to this commit fix it?

**Comment by bvernoux** [comment]
It seems this issue is also affected by the new bug https://github.com/glscopeclient/scopehal-apps/issues/436 (newly introduced in latest fix ?? as I have never seen that in older glscopeclient used 1 week ago), so I will wait this bug to be fixed before

**Comment by azonenberg** [comment]
Please check if f1d109bbd4c8d4d3553beab9bfa08da5f1638c5d fixes the rendering issue.

**Comment by bvernoux** [comment]
This issue is related to https://github.com/glscopeclient/scopehal-apps/issues/436

**Comment by azonenberg** [comment]
Closing this and tracking #442 as a separate issue for "markers don't work in sessions without an attached scope".
