### ISSUE TITLE
Add a way to truncate waveform(s)

### ISSUE THREAD

**Issue by bvernoux** [glscopeclient/scopehal-apps#437]
Add a way to keep data waveform(s) with start and end markers for example to keep only the part between markers
This will be applied on all waveform(s) if there is several waveforms displayed.
Main idea is to have a special export feature which truncate data.

- This feature is a must have to filter / export only required data as in raw capture there is often too much "non" interesting data to be removed to keep only interesting data.
- This feature will also help to do better/faster Issue report on smaller data set

**Comment by azonenberg** [comment]
@602p can we close this now that you have the clip filter?

**Comment by 602p** [comment]
Not sure this ask is fully met since the window filter still stores the entire waveform in the history etc. But it's largely solved.

**Comment by bvernoux** [comment]
So far Clip (tested in nglscopeclient) does not allow to cut a signal (left & right par for example) but clip on top/bottom

**Comment by 602p** [comment]
@bvernoux I believe azonenberg made a typo; the 'Window' filter allows selecting a temporal subset of a waveform
