### ISSUE TITLE
Feature request: highlight waveform span when using protocol analyzer

### ISSUE THREAD

**Issue by dan-gies** [glscopeclient/scopehal-apps#542]
Apologies if this isn't the right place to put feature requests.

I'm using the protocol analyzer, and find it incredibly useful to click on different packets in the protocol analyzer to jump to the timestamp in the waveform. However, when the waveform is zoomed out, it can be tough to tell what the highlighted (grey) packet refers to on the waveform. It would be great to have a same-colored bar on the time axis to indicate where in the waveform the packet refers:

![image](https://user-images.githubusercontent.com/108100309/200353859-2f8f8309-26d7-4403-b8e9-46a7866ebe2c.png)

**Comment by azonenberg** [comment]
If you have an X axis cursor enabled, it should jump to the start of the packet when you select one.

**Comment by dan-gies** [comment]
This works well! Thanks.
