### ISSUE TITLE
Attempting to add multiple instruments at the same time breaks pop-up/input fields

### ISSUE THREAD

**Issue by Johnsel** [glscopeclient/scopehal-apps#615]
To replicate my issue use the Add->Generator->Connect menu, then click Add->Oscilloscope->Connect, without first adding the Generator.

This will make the Add Function Generator pop-up contain 2 sets of input fields, but they are broken.

![image](https://github.com/glscopeclient/scopehal-apps/assets/537075/cb04256a-b754-4d13-9b3d-b09db81a63c6)

**Comment by azonenberg** [comment]
Easy fix, use unique imgui ID for all "add XX" dialogs. I don't think any other code actually relies on these being single instance dialogs.

Will work on this later today.
